import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/_next/static/*',
          '/_next/image*',
          '/sitemap.xml',
          '/sitemap-noor.xml',
          '/robots.txt',
          '/prayer-times',
          '/quran',
          '/guides',
          '/hajj-umrah',
          '/zakat',
          '/janazah',
          '/duas',
          '/ziyarat',
          '/ziyarat/*',
          '/search',
          '/travel',
          '/etiquette',
          '/nikah',
          '/kids',
          '/qibla',
          '/watch',
          '/calendar',
          '/media',
          '/app-preview',
          '/contact',
          '/llms.txt',
          '/llms-full.txt',
          '/.well-known/*',
        ],
        disallow: [
          '/dashboard',
          '/super-admin',
          '/admin',
          '/api/admin/*',
          '/api/auth/*',
        ],
      },
      // Googlebot explicit rule ensuring zero crawling obstacles
      {
        userAgent: ['Googlebot', 'Googlebot-Mobile', 'Googlebot-Image'],
        allow: [
          '/',
          '/_next/static/*',
          '/_next/image*',
          '/sitemap.xml',
          '/sitemap-noor.xml',
          '/robots.txt',
          '/prayer-times',
          '/quran',
          '/guides',
          '/hajj-umrah',
          '/zakat',
          '/janazah',
          '/duas',
          '/ziyarat',
          '/ziyarat/*',
          '/search',
          '/travel',
          '/etiquette',
          '/nikah',
          '/kids',
          '/qibla',
          '/watch',
          '/calendar',
          '/media',
          '/app-preview',
          '/contact',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: [
          '/dashboard',
          '/super-admin',
          '/admin',
          '/api/admin/*',
          '/api/auth/*',
        ],
      },
      // Answer Engine Optimization (AEO) & Generative Engine Optimization (GEO) Bots
      {
        userAgent: [
          'GPTBot',
          'OAI-SearchBot',
          'ChatGPT-User',
          'ClaudeBot',
          'Claude-Web',
          'PerplexityBot',
          'Google-Extended',
          'Applebot-Extended',
          'Amazonbot',
          'cohere-ai',
          'Meta-ExternalAgent',
          'Bytespider',
          'Diffbot',
        ],
        allow: [
          '/',
          '/_next/static/*',
          '/_next/image*',
          '/prayer-times',
          '/quran',
          '/guides',
          '/hajj-umrah',
          '/zakat',
          '/janazah',
          '/duas',
          '/ziyarat',
          '/ziyarat/*',
          '/search',
          '/travel',
          '/etiquette',
          '/nikah',
          '/kids',
          '/qibla',
          '/watch',
          '/calendar',
          '/media',
          '/app-preview',
          '/contact',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: [
          '/dashboard',
          '/super-admin',
          '/admin',
          '/api/admin/*',
          '/api/auth/*',
        ],
      },
    ],
    sitemap: [
      'https://www.nooreilahi.com/sitemap.xml',
      'https://www.nooreilahi.com/sitemap-noor.xml',
    ],
    host: 'https://www.nooreilahi.com',
  };
}


